import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
  products: defineTable({
    title: v.string(),
    imageId: v.string(),
    price: v.number(),
  }),
  todos: defineTable({
    text: v.string(),
    completed: v.boolean(),
  }),
  claims: defineTable({
    claimNumber: v.string(),
    policyId: v.string(),
    customerId: v.string(),
    vehicleId: v.optional(v.string()),
    driverId: v.optional(v.string()),
    providerId: v.optional(v.string()),
    customerAge: v.number(),
    lineOfBusiness: v.optional(
      v.union(
        v.literal('vehicles'),
        v.literal('health'),
        v.literal('life'),
        v.literal('home'),
        v.literal('general'),
      ),
    ),
    coverage: v.optional(v.string()),
    claimType: v.union(
      v.literal('collision'),
      v.literal('theft'),
      v.literal('injury'),
      v.literal('glass'),
      v.literal('fire'),
      v.literal('other'),
    ),
    channel: v.union(
      v.literal('app'),
      v.literal('broker'),
      v.literal('callcenter'),
      v.literal('web'),
    ),
    locationRegion: v.string(),
    branch: v.optional(v.string()),
    vehicleYear: v.number(),
    vehicleMake: v.optional(v.string()),
    vehicleModel: v.optional(v.string()),
    licensePlateHash: v.optional(v.string()),
    claimAmount: v.number(),
    estimatedDamageAmount: v.number(),
    paidAmount: v.optional(v.number()),
    claimStatus: v.optional(v.string()),
    sumInsured: v.optional(v.number()),
    deductible: v.optional(v.number()),
    incidentsLast12Months: v.number(),
    incidentsLast18Months: v.optional(v.number()),
    vehicleIncidentsLast18Months: v.optional(v.number()),
    driverIncidentsLast18Months: v.optional(v.number()),
    priorRcClaims: v.optional(v.number()),
    daysSincePolicyStart: v.number(),
    daysUntilPolicyEnd: v.optional(v.number()),
    daysBetweenOccurrenceReport: v.optional(v.number()),
    occurredAt: v.number(),
    submittedAt: v.number(),
    isNightClaim: v.boolean(),
    documentsComplete: v.optional(v.boolean()),
    missingCriticalDocument: v.optional(v.boolean()),
    documentsInconsistent: v.optional(v.boolean()),
    beneficiaryType: v.optional(v.string()),
    providerObservedCases: v.optional(v.number()),
    providerInWatchlist: v.optional(v.boolean()),
    accidentDynamics: v.optional(v.string()),
    unidentifiedThirdParty: v.optional(v.boolean()),
    narrativeSimilarityMax: v.optional(v.number()),
    narrativeGroup: v.optional(v.string()),
    customerSegment: v.optional(v.string()),
    customerTenureMonths: v.optional(v.number()),
    customerPoliciesCount: v.optional(v.number()),
    customerDelinquent: v.optional(v.boolean()),
    customerScoreSimulated: v.optional(v.number()),
    fraudLabelSimulated: v.optional(v.number()),
    mlFraudProbability: v.optional(v.number()),
    mlRiskScore: v.optional(v.number()),
    mlModelVersion: v.optional(v.string()),
    reportNarrative: v.string(),
    source: v.optional(v.union(v.literal('synthetic'), v.literal('public'))),
    sourceDataset: v.optional(v.string()),
  })
    .index('by_submitted_at', ['submittedAt'])
    .index('by_customer', ['customerId'])
    .index('by_provider', ['providerId'])
    .index('by_vehicle', ['vehicleId'])
    .index('by_risk_model', ['mlRiskScore'])
    .index('by_claim_type', ['claimType'])
    .index('by_source', ['source']),
  policies: defineTable({
    policyId: v.string(),
    customerId: v.string(),
    vehicleId: v.optional(v.string()),
    lineOfBusiness: v.string(),
    startAt: v.number(),
    endAt: v.number(),
    premium: v.number(),
    sumInsured: v.number(),
    deductible: v.number(),
    salesChannel: v.string(),
    city: v.string(),
    status: v.string(),
  })
    .index('by_policy_id', ['policyId'])
    .index('by_customer', ['customerId']),
  insureds: defineTable({
    customerId: v.string(),
    segment: v.string(),
    tenureMonths: v.number(),
    city: v.string(),
    policiesCount: v.number(),
    claimsLast12Months: v.number(),
    delinquent: v.boolean(),
    customerScoreSimulated: v.number(),
  }).index('by_customer_id', ['customerId']),
  vehicles: defineTable({
    vehicleId: v.string(),
    customerId: v.string(),
    licensePlateHash: v.string(),
    chassisHash: v.string(),
    engineHash: v.string(),
    make: v.string(),
    model: v.string(),
    year: v.number(),
  })
    .index('by_vehicle_id', ['vehicleId'])
    .index('by_customer', ['customerId']),
  providers: defineTable({
    providerId: v.string(),
    type: v.string(),
    city: v.string(),
    associatedClaims: v.number(),
    averageClaimAmount: v.number(),
    observedCaseRate: v.number(),
    tenureMonths: v.number(),
    inWatchlist: v.boolean(),
  }).index('by_provider_id', ['providerId']),
  claimDocuments: defineTable({
    documentId: v.string(),
    claimNumber: v.string(),
    documentType: v.string(),
    delivered: v.boolean(),
    legible: v.boolean(),
    issuedAt: v.number(),
    inconsistencyDetected: v.boolean(),
    observation: v.optional(v.string()),
  }).index('by_claim_number', ['claimNumber']),
})
