/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Importacion_csvRouteImport } from './routes/importacion_csv'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as ML_AGENTERouteImport } from './routes/ML_AGENTE'
import { Route as IndexRouteImport } from './routes/index'

const Importacion_csvRoute = Importacion_csvRouteImport.update({
  id: '/importacion_csv',
  path: '/importacion_csv',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const ML_AGENTERoute = ML_AGENTERouteImport.update({
  id: '/ML_AGENTE',
  path: '/ML_AGENTE',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ML_AGENTE': typeof ML_AGENTERoute
  '/casos': typeof CasosRoute
  '/importacion_csv': typeof Importacion_csvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ML_AGENTE': typeof ML_AGENTERoute
  '/casos': typeof CasosRoute
  '/importacion_csv': typeof Importacion_csvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ML_AGENTE': typeof ML_AGENTERoute
  '/casos': typeof CasosRoute
  '/importacion_csv': typeof Importacion_csvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ML_AGENTE' | '/casos' | '/importacion_csv'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ML_AGENTE' | '/casos' | '/importacion_csv'
  id: '__root__' | '/' | '/ML_AGENTE' | '/casos' | '/importacion_csv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ML_AGENTERoute: typeof ML_AGENTERoute
  CasosRoute: typeof CasosRoute
  Importacion_csvRoute: typeof Importacion_csvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/importacion_csv': {
      id: '/importacion_csv'
      path: '/importacion_csv'
      fullPath: '/importacion_csv'
      preLoaderRoute: typeof Importacion_csvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ML_AGENTE': {
      id: '/ML_AGENTE'
      path: '/ML_AGENTE'
      fullPath: '/ML_AGENTE'
      preLoaderRoute: typeof ML_AGENTERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ML_AGENTERoute: ML_AGENTERoute,
  CasosRoute: CasosRoute,
  Importacion_csvRoute: Importacion_csvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
